### PR TITLE
Add getopts and Shark

### PR DESCRIPTION
**Pull request by bucaran**
* Move Fishtape below dispatch.
* Add getopts just below Fishtape.
* Add Shark just above Spark.

### CODE REVIEW

**Comment by sgoings** [comment]
Seems like these are all fish related... why not put them in the fish section?

**Comment by bucaran** [comment]
@sgoings I agree and there are also other inconsistencies. 

I am also maintaining [this list](https://github.com/bucaran/awesome-fish).

What do you think would be the best thing to do?

**Comment by sgoings** [comment]
Maybe we could point the fish shell section to your awesome-fish repo? Interested to hear @alebcay's ideas on organization now that this list of utilities has grown quite nicely.

**Comment by bucaran** [comment]
@sgoings That could work. Let's see what @alebcay have to say.

**Comment by alebcay** [comment]
That sounds like a good idea. Lately, there's been a lot of zsh/fish stuff flowing in, and it felt awfully repetitive. I'll probably replace the zsh/fish sections with links to respective awesome lists and focus this section more on shell-agnostic stuff.

**Comment by bucaran** [comment]
@alebcay SGTM :+1:

**Comment by bucaran** [comment]
I can help with the fish, part. Exactly what do you want to do?

* Remove Fish links.
* Add conspicuous links [Awesome Fish Shell](https://github.com/bucaran/awesome-fish)
* Anything else?

**Comment by alebcay** [comment]
@bucaran Remove Fish links, link to your Awesome Fish Shell (e.g. make a separate Fish shell section with a single line, "See Awesome Fish Shell", or something like that). If there's any fish-related stuff on here that's not on your list yet, it would be great if you added it so that we don't lose anything.

The course of action for zsh stuff will be similar.

**Comment by bucaran** [comment]
@alebcay Great. I will work on it right away.

**Comment by alebcay** [comment]
Could you please resubmit/fix this? Again, `shark` and `getopts` can stay (glad to see that Fishtape has found its home elsewhere).

**Pull request closed without merging**
