### PR TITLE
add facy: command line power tool for facebook

### PR DESCRIPTION
**Pull request by huydx**
Hi @alebcay , i've added the command line tool i wrote before, which used to access facebook inside your terminal. Please take a look, and feedbacks are welcome.
Thank you.

### CODE REVIEW

**Comment by huydx** [comment]
ping @alebcay

**Comment by alebcay** [comment]
Please place it alphabetically in write spot in the "Applications" section.

**Comment by jscappini** [comment]
@huydx Don't want to be nosy, but is Facy really working? I tried it with no luck, and there is open issues showing the same problem I have since January... Just saying. :eyes:

**Comment by huydx** [comment]
@jscappini can you please report the detail issue in my repo ;). tks

**Comment by alebcay** [comment]
@jscappini as long as it has some functionality and is under active development, it should be alright to include here.

**Comment by huydx** [comment]
@alebcay fixed it, please give a check :). many thanks

**Pull request merged**
