### PR TITLE
Add Chinese translation

### PR DESCRIPTION
**Pull request by xuxiaodong**

### CODE REVIEW

**Comment by alebcay** [comment]
Thanks! Are you willing to maintain it and keep up with changes?

**Comment by xuxiaodong** [comment]
Yes. Thank you!



—
~ toy

**Comment by alebcay** [comment]
Awesome! Thanks again!

**Comment by jlevy** [comment]
https://github.com/Psycho7 has done the same thing for https://github.com/jlevy/the-art-of-command-line

Mentioning here since you both may be able to help each other review the translations and keep them up to date.

See https://github.com/jlevy/the-art-of-command-line/issues/82

**Pull request merged**
