### PR TITLE
Add procdog, a tool for controlling long-lived processes.

### PR DESCRIPTION
**Pull request by jlevy**
Another contribution of my own. Obscure but useful. ;)

### CODE REVIEW

**Comment by tayloring** [comment]
hello

**Comment by alebcay** [comment]
I feel that `procdog` would fit better under "System Utilities" than "For Developers", since it's more of a sysadmin tool and isn't restricted to only software development. What are your thoughts on that?

**Comment by jlevy** [comment]
I'd considered that but hesitated, probably because I'd made the "System Utilities" description too narrow. Maybe I'll broaden that description too, to include all OS, file, and process-related tools.

**Comment by jlevy** [comment]
Better?

**Comment by alebcay** [comment]
Sure, let's go for it.

**Pull request merged**
