### PR TITLE
add development tools

### PR DESCRIPTION
**Pull request by nodiscc**
* optparse
 * shellfire

### CODE REVIEW

**Comment by nodiscc** [comment]
@alebcay Ok to merge?

**Comment by alebcay** [comment]
Yes, I forgot about this. Thanks for the reminder.

**Comment by jawshooah** [comment]
Seems like optparse belongs in awesome-bash if it's exclusive to bash, don't you think?

**Comment by jawshooah** [comment]
Never mind, didn't realize that split never happened.

**Comment by alebcay** [comment]
It's planned, but I've never gotten around to it. Also, is it exclusive to Bash? I know the examples given are Bash, but would they work in Zsh/etc.?

**Pull request merged**
