### PR TITLE
Add xiringuito - SSH-based "VPN for poors"

### PR DESCRIPTION
**Pull request by ivanilves**
This adds xiringuito - SSH-based "VPN for poors"

# WHY?
`xiringuito` is awesome, because:
* easy to install (no dependencies, no configurations)
* allows you to manage one, few or many connections easily (and connect em simultaneously if you want)
* it has `xaval` connection manager - a tool that may record and later re-use your connection profiles
* though you are free to use or not to use `xaval` connection manager - people also use `xiringuito` for ad-hoc onetime connections
* Just look at this GIF :wink:

### CODE REVIEW

**Comment by ivanilves** [comment]
can't get why it's red ... :sob:

**Comment by booyaa** [comment]
It's not you, some of the existing links have failed, one of will look to resolve this.

```
> Links 
  1. [L147] 301 http://pre-commit.com  → https://pre-commit.com/ 
  2. [L272] 301 https://github.com/jmcantrell/bashful  → https://github.com/plytophogy/bashful 
```

**Comment by ivanilves** [comment]
Got it! Thanks!

**Comment by ivanilves** [comment]
Hey! :wave: 

Why not merge it? :innocent: 

ping @alebcay

**Comment by ivanilves** [comment]
Closed due inactivity :ghost:

**Comment by ivanilves** [comment]
Thanks @alebcay :heart: :clap:

**Pull request merged**
