### PR TITLE
Add Kapow! CLI to HTTP server

### PR DESCRIPTION
**Pull request by panchoh**
`Kapow!` lets you expose shell scripts over HTTP, retaining full control
on both the parameters accepted and how the output is sent.

Written in Go.

Full docs: https://kapow.readthedocs.io

Disclaimer: I'm one of the authors! Self-promotion alert! ;-)

### CODE REVIEW

**Comment by panchoh** [comment]
Hi!
We got 500+ stars on GitHub \o/, any chance this PR might be accepted?
Cheers,

**Comment by panchoh** [comment]
Here's the reference to the [repo](https://github.com/BBVA/kapow) on GitHub, if that helps.

@alebcay, what did we do wrong?  (PR still not accepted after almost four years).
Anything I can do to clear this?)

Thanks in advance!

**Comment by alebcay** [comment]
Hi @panchoh, sorry to keep you waiting. The long wait is my fault, nothing you did wrong - it slipped past me.

Congrats on the growth of the project! Merging this now before I get distracted again 😅

**Comment by alebcay** [comment]
GitHub's web UI seems to have trouble merging this (it's probably too old), so I had to apply it manually in https://github.com/alebcay/awesome-shell/commit/5fa5475a3a533efaf812a900b8926c61e2a4f5a0.

**Comment by panchoh** [comment]
Thanks, @alebcay!

**Pull request closed without merging**
