### PR TITLE
Adding MultiTail

### PR DESCRIPTION
**Pull request by jonatan-ivanov**

### CODE REVIEW

**Review by alivx — APPROVED** [review]
Handy tool :)

**Comment by alebcay** [comment]
Source repository is gone :(

**Comment by jonatan-ivanov** [comment]
@alebcay You mean this? https://github.com/jonatan-ivanov/awesome-shell/tree/patch-4

**Comment by i5513** [comment]
> @alebcay You mean this? https://github.com/jonatan-ivanov/awesome-shell/tree/patch-4

He said about 404 error at multitail link

Regards

**Pull request closed without merging**
